"""Cryptographically secure random material generation."""

from __future__ import annotations

import base64
import secrets
import uuid

from cryptosuite.utils.exceptions import ValidationError

MAX_RANDOM_BYTES = 1024 * 1024


def random_bytes(length: int) -> bytes:
    """Return bytes from the operating system CSPRNG."""
    if isinstance(length, bool) or not isinstance(length, int):
        raise ValidationError("Random byte length must be an integer.")
    if not 1 <= length <= MAX_RANDOM_BYTES:
        raise ValidationError(
            f"Random byte length must be between 1 and {MAX_RANDOM_BYTES}."
        )
    return secrets.token_bytes(length)


def random_hex(length: int) -> str:
    """Return a lowercase hexadecimal encoding of random bytes."""
    return random_bytes(length).hex()


def random_urlsafe(length: int) -> str:
    """Return a URL-safe token containing at least ``length`` random bytes."""
    if isinstance(length, bool) or not isinstance(length, int):
        raise ValidationError("Random byte length must be an integer.")
    if not 1 <= length <= MAX_RANDOM_BYTES:
        raise ValidationError(
            f"Random byte length must be between 1 and {MAX_RANDOM_BYTES}."
        )
    return secrets.token_urlsafe(length)


def random_base64(length: int) -> str:
    """Return standard Base64 encoding of exactly ``length`` random bytes."""
    return base64.b64encode(random_bytes(length)).decode("ascii")


def random_uuid() -> str:
    """Return a UUIDv4 generated by the operating-system CSPRNG."""
    return str(uuid.UUID(bytes=random_bytes(16), version=4))
